FROM lscr.io/linuxserver/webtop:fedora-kde

RUN dnf update -y \
    && dnf -y upgrade \
    && dnf -y install git wget \
    && dnf -y install R \
    && wget https://download.documentfoundation.org/libreoffice/stable/7.4.0/rpm/x86_64/LibreOffice_7.4.0_Linux_x86-64_rpm.tar.gz \
    && tar -xvf LibreOffice_7.4.0_Linux_x86-64_rpm.tar.gz \
    && cd LibreOffice_7.4.0.3_Linux_x86-64_rpm \
    && dnf -y install RPMS/*.rpm \
    && cd \
    && dnf -y install pspp