FROM lscr.io/linuxserver/webtop:fedora-kde

RUN dnf update -y \
    && dnf -y upgrade \
    && dnf -y install git wget \
    && dnf -y install R \
    #&& wget https://www.libreoffice.org/donate/dl/rpm-x86_64/7.3.7/de/LibreOffice_7.3.7_Linux_x86-64_rpm.tar.gz \
    #&& tar -xvf LibreOffice_7.3.7_Linux_x86-64_rpm.tar.gz \
    #&& cd LibreOffice_7.4.0.3_Linux_x86-64_rpm \
    #&& dnf -y install RPMS/*.rpm \
    #&& cd \
    && dnf -y install pspp